# Generated by Django 5.2.4 on 2025-07-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Category_Image', models.ImageField(blank=True, null=True, upload_to='Category Images')),
                ('Category_Description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
