# Generated by Django 5.2.4 on 2025-07-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0002_productdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='Price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
