# Generated by Django 5.2.4 on 2025-07-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Password', models.CharField(blank=True, max_length=50, null=True)),
                ('C_Password', models.CharField(blank=True, max_length=50, null=True)),
                ('E_Mail', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
