# Generated by Django 5.2.4 on 2025-07-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=50, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity', models.CharField(blank=True, null=True)),
                ('Price', models.CharField(blank=True, null=True)),
                ('TotalPrice', models.CharField(blank=True, null=True)),
                ('Product_Image', models.ImageField(blank=True, null=True, upload_to='Cart_Image')),
            ],
        ),
    ]
