# Generated by Django 5.2.4 on 2025-08-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_contactdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
