# Generated by Django 5.2.4 on 2025-08-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_alter_cartdb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='TotalPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
