# Generated by Django 5.2.4 on 2025-08-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_alter_cartdb_quantity_alter_cartdb_totalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Place', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('TotalPrice', models.IntegerField(blank=True, null=True)),
                ('PIN_CODE', models.IntegerField(blank=True, null=True)),
                ('Mobile_Number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
