# Generated by Django 5.2.4 on 2025-08-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_orderdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='State',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
