# Generated by Django 5.2.4 on 2025-08-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_orderdb_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='Total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
